stages:
  # - prepare
  - build_and_test

# If you are looking for a place where to add 'UNITY_LICENSE_FILE' and other secrets, please visit your project's gitlab page:
# settings > CI/CD > Variables instead
variables:
  BUILD_NAME: ExampleProjectName
  UNITY_ACTIVATION_FILE: ./unity3d.alf
  IMAGE: unityci/editor # https://hub.docker.com/r/unityci/editor
  IMAGE_VERSION: 1 # This will automatically use latest v1.x.x, see https://github.com/game-ci/docker/releases
  UNITY_DIR: $CI_PROJECT_DIR # this needs to be an absolute path. Defaults to the root of your tree.
  # You can expose this in Unity via Application.version
  VERSION_NUMBER_VAR: $CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID-$CI_JOB_ID
  VERSION_BUILD_VAR: $CI_PIPELINE_IID
  UNITY_VERSION: 2022.3.40f1-base-3.1.0

image: $IMAGE:$UNITY_VERSION-base-$IMAGE_VERSION

# get-unity-version:
#   image: alpine
#   stage: prepare
#   variables:
#     GIT_DEPTH: 1
#   script:
#     - echo UNITY_VERSION=$(cat $UNITY_DIR/ProjectSettings/ProjectVersion.txt | grep "m_EditorVersion:.*" | awk '{ print $2}') | tee prepare.env
#   artifacts:
#     reports:
#       dotenv: prepare.env

.cache: &cache
  cache:
    key: "$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG-$TEST_PLATFORM"
    paths:
      - $UNITY_DIR/Library/


.unity_defaults: &unity_defaults
  <<:
    # - *unity_before_script
    - *cache

test:
  stage: build_and_test
  <<: *unity_defaults
  script:
    - echo "Running play mode tests..."
    - unity-editor -projectPath . -runTests -batchmode -nographics -silent-crashes -testPlatform PlayMode -logfile playmode-results.log
  artifacts:
    paths:
      - playmode-results.log
